"""empty message

Revision ID: 15faab22a8b4
Revises: 4b8bed9174ab
Create Date: 2020-07-18 19:04:10.853649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15faab22a8b4'
down_revision = '4b8bed9174ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'activity', 'account', ['website'], ['website'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity', type_='foreignkey')
    # ### end Alembic commands ###
