"""empty message

Revision ID: 4b8bed9174ab
Revises: ee2e06d679c1
Create Date: 2020-07-15 20:07:42.263067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b8bed9174ab'
down_revision = 'ee2e06d679c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('website', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'website')
    # ### end Alembic commands ###
