"""empty message

Revision ID: 510cad439897
Revises: c9002b5d1177
Create Date: 2020-07-14 22:40:01.489143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510cad439897'
down_revision = 'c9002b5d1177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('enclosure', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video',
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=False),
    sa.Column('thumbnail', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    op.drop_table('activity')
    # ### end Alembic commands ###
