"""empty message

Revision ID: 6b26915f2679
Revises: 15faab22a8b4
Create Date: 2020-07-18 19:07:50.709748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b26915f2679'
down_revision = '15faab22a8b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity', type_='foreignkey')
    # ### end Alembic commands ###
