"""art table

Revision ID: b34b5f9a88e6
Revises: d1b403f1420c
Create Date: 2020-07-11 23:12:19.956789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b34b5f9a88e6'
down_revision = 'd1b403f1420c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('art')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('art',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=32), nullable=False),
    sa.Column('src', sa.VARCHAR(length=128), nullable=True),
    sa.Column('description', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('orientation', sa.VARCHAR(length=32), nullable=True),
    sa.Column('name', sa.VARCHAR(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
