"""art table

Revision ID: d1b403f1420c
Revises: 56e8827d890b
Create Date: 2020-07-11 23:03:46.750742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1b403f1420c'
down_revision = '56e8827d890b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.alter_column('art', 'category',
               existing_type=sa.VARCHAR(length=32))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('art', 'category',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_column('art', 'name')
    # ### end Alembic commands ###
