"""nicknames table

Revision ID: d62b8d73aaf5
Revises: 
Create Date: 2020-07-11 15:59:43.379975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62b8d73aaf5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nickname',
    sa.Column('nickname', sa.String(length=32), nullable=False),
    sa.Column('create_date_str', sa.String(length=64), nullable=True),
    sa.Column('create_date', sa.Date(), nullable=True),
    sa.Column('history', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('nickname')
    )
    op.create_table('account',
    sa.Column('website', sa.String(length=32), nullable=False),
    sa.Column('nickname', sa.String(length=32), nullable=True),
    sa.Column('link', sa.String(length=120), nullable=True),
    sa.Column('profile_pic', sa.String(length=120), nullable=True),
    sa.Column('logo', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['nickname'], ['nickname.nickname'], ),
    sa.PrimaryKeyConstraint('website')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    op.drop_table('nickname')
    # ### end Alembic commands ###
